version: '3.8'
services:
  nvmaskrcnn:
    build:
      context: ./
    working_dir: '/root/'
    volumes:
      - ./opt:/root/opt
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [utility, compute, video]